### PR TITLE
Fix fatal error trying to call functions on null.

### PR DESCRIPTION
**Pull request by Alexia**

### CODE REVIEW

**Comment by xbony2** [comment]
You sneaked this patch into the wiki already, didn't you? ;)

**Comment by Alexia** [comment]
Yep, SysOps wasn't happy about all the error reports.  :D

**Comment by xbony2** [comment]
Santa had messed up; {{#headcount:}} was being applied incorrectly in the sidebar, so the count became "Could not retrieve revision from Special:RecentChanges" :P

**Comment by elifoster** [comment]
Oh, yeah, that is not something I had considered :P

**Pull request merged**
